---
title: "In-class Exercise 4"
author: "Magdalene Chan"
date: "4 February 2023"
date-modified: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
format: html
editor: visual
---

```{r}
pacman::p_load(plotly, DT, patchwork, ggstatsplot, tidyverse, ggside, readxl, performance, parameters, see)
```

# Exam Data Set

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

```{r, fig.width=12,fig.height=6}
plot_ly(data = exam_data, 
        x = ~ENGLISH, 
        y = ~MATHS, 
        color = ~RACE)
```

```{r, fig.width=12,fig.height=6}
p <- ggplot(data=exam_data, 
            aes(x = MATHS,
                y = ENGLISH)) +
  geom_point(size = 1) +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100))
ggplotly(p) #<<
```

```{r, fig.width=12,fig.height=6}
ggbetweenstats(
  data = exam_data,
  x = GENDER, 
  y = MATHS,
  type = "p",
  messages = FALSE
)
```

```{r, fig.width=12,fig.height=6}
ggscatterstats(
  data = exam_data,
  x = MATHS, 
  y = ENGLISH,
  marginal = TRUE
)
```

```{r}
my_sum <- exam_data %>%
  group_by(RACE) %>%
  summarise(
    n=n(),
    mean=mean(MATHS),
    sd=sd(MATHS)
    ) %>%
  mutate(se=sd/sqrt(n-1))

ggplot(my_sum) +
  geom_errorbar(
    aes(x=RACE, 
        ymin=mean-se, 
        ymax=mean+se), 
    width=0.2, 
    colour="black", 
    alpha=0.9, 
    linewidth=0.5) +
  geom_point(aes
           (x=RACE, 
            y=mean), 
           stat="identity", 
           color="red",
           size = 1.5,
           alpha=1) +
  ggtitle("Standard error of mean maths score by race")
```

# Toyota Data Set

```{r, fig.width=12,fig.height=6}
car_resale <- read_xls("data/ToyotaCorolla.xls", "data")

car_resale
```

```{r, fig.width=12,fig.height=6}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + Weight + Guarantee_Period, 
            data = car_resale)
model
```

```{r, fig.width=12,fig.height=6}
check_c <- check_collinearity(model)
plot(check_c)
```

```{r, fig.width=12,fig.height=6}
model1 <- lm(Price ~ Age_08_04 + KM + Weight + Guarantee_Period, 
             data = car_resale)

check_n <- check_normality(model1)

plot(check_n)
```

```{r, fig.width=12,fig.height=8}
check_model(model1)
```
